name: Docker-ex-node
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports: 
          - 3002:3000
      mongo:
        image: mongo
        ports: 
          - "27017:27017"
    steps:
        - name: post a user
          run: echo "hello"
        - name: Get users
          run: echo "hello world"
